import { Sequelize } from "sequelize-typescript";
import request from "supertest";
import { setupDb } from "../../db/sequelize";
import { app } from "../express";

describe("E2E test for invoice", () => {
  let sequelize: Sequelize;

  beforeEach(async () => {
    sequelize = await setupDb();
  });

  afterEach(async () => {
    await sequelize.close();
  });

  it("should find an invoice generated by checkout", async () => {
    await request(app)
      .post("/clients")
      .send({
        id: "c1",
        name: "John",
        email: "john@email.com",
        document: "123.456.789-00",
        address: {
          street: "Rua 123",
          number: "99",
          complement: "Casa Verde",
          city: "Criciúma",
          state: "SC",
          zipCode: "88888-888",
        },
      });
    await request(app).post("/products").send({
      id: "p1",
      name: "Product 1",
      description: "Product 1 description",
      purchasePrice: 100,
      salesPrice: 200,
      stock: 10,
    });
    await request(app).post("/products").send({
      id: "p2",
      name: "Product 2",
      description: "Product 2 description",
      purchasePrice: 50,
      salesPrice: 100,
      stock: 10,
    });

    const checkout = await request(app)
      .post("/checkout")
      .send({
        clientId: "c1",
        products: [{ productId: "p1" }, { productId: "p2" }],
      });
    expect(checkout.status).toBe(201);
    const invoiceId = checkout.body.invoiceId;

    const response = await request(app).get(`/invoice/${invoiceId}`);

    expect(response.status).toBe(200);
    expect(response.body.id).toBe(invoiceId);
    expect(response.body.name).toBe("John");
    expect(response.body.document).toBe("123.456.789-00");
    expect(response.body.street).toBe("Rua 123");
    expect(response.body.number).toBe("99");
    expect(response.body.complement).toBe("Casa Verde");
    expect(response.body.city).toBe("Criciúma");
    expect(response.body.state).toBe("SC");
    expect(response.body.zipCode).toBe("88888-888");
    expect(response.body.items).toEqual([
      { id: "p1", name: "Product 1", price: 200 },
      { id: "p2", name: "Product 2", price: 100 },
    ]);
    expect(response.body.total).toBe(300);
    expect(response.body.createdAt).toBeDefined();
  });

  it("should return 404 when invoice does not exist", async () => {
    const response = await request(app).get("/invoice/unknown");

    expect(response.status).toBe(404);
    expect(response.body.message).toBe("Invoice not found");
  });
});
